services:
  member-service:
    build: ./services/member_service
    container_name: member-service
    ports:
      - "8000:8000"
      - "50051:50051"
  board-service:
    build: ./services/board_service
    container_name: board-service
    ports:
      - "8001:8001"
    depends_on:
      - member-service
